const FETCH_COLLECTION = 'CRUD_FETCH_COLLECTION';
const FETCH_COLLECTION_SUCCESS = 'CRUD_FETCH_COLLECTION_SUCCESS';
const FETCH_COLLECTION_FAILURE = 'CRUD_FETCH_COLLECTION_FAILURE';
const FETCH_ONE = 'CRUD_FETCH_ONE';
const FETCH_ONE_SUCCESS = 'CRUD_FETCH_ONE_SUCCESS';
const FETCH_ONE_FAILURE = 'CRUD_FETCH_ONE_FAILURE';

export {
  FETCH_COLLECTION,
  FETCH_COLLECTION_SUCCESS,
  FETCH_COLLECTION_FAILURE,
  FETCH_ONE,
  FETCH_ONE_SUCCESS,
  FETCH_ONE_FAILURE,
};
